### ISSUE TITLE
Plugin reports an error "Couldn't find a valid Jira issue key."

### ISSUE THREAD

**Issue by soritchie** [adyscorpius/logseq-jira#5] opened 2023-05-11 13:28 UTC
I'm using version 0.0.9 of the plugin. It worked as expected this morning, but after I upgraded Logseq to v0.9.5 I now consistently get the following error when trying to invoke the plugin: "Couldn't find a valid Jira issue key."

I'm not sure if the Logseq upgrade affected the plugin, or if it's a coincidence.

I regenerated a new Jira API token, but the issue remains.

**Comment by adyscorpius** [comment] 2023-05-11 17:59
I can confirm this started happening since Logseq updated to 0.9.5

Seems like they changed something in how plugins access the plugin settings. I'll have a look and fix it soon. I could replicate the same error with the OpenAI plugin too.

**Comment by adyscorpius** [comment] 2023-05-11 23:30
https://github.com/logseq/logseq/issues/9359

Here's an issue tracking this. Affects multiple plugins. I'll see if they fix it soon, else I'll find a workaround.

**Comment by soritchie** [comment] 2023-05-12 08:09
Thanks!

**Comment by adyscorpius** [comment] 2023-05-12 13:50
Updating to 0.9.6 fixed the issue for me. If you can confirm this, I'll close the issue.

**Closed** 2023-05-16 12:01 UTC
